apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-victorialogs
  namespace: keep-dev
  labels:
    app: mcp-victorialogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-victorialogs
  template:
    metadata:
      labels:
        app: mcp-victorialogs
    spec:
      containers:
        - name: mcp-victorialogs
          image: ghcr.io/victoriametrics-community/mcp-victorialogs:latest
          ports:
            - containerPort: 8081
          env:
            - name: VL_INSTANCE_ENTRYPOINT
              value: http://vlsingle-vlogs-ha.victorialogs.svc:9428
            - name: MCP_SERVER_MODE
              value: http
            - name: MCP_LISTEN_ADDR
              value: ':8081'
          imagePullPolicy: Always